name: Publish Docker

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    step:
      - uses: actions/checkout@main
      - name: Publish to registry
      - uses: elgohr/Publish-Docker-Github-Action@master
      with:
        registry: docker.pkg.github.com
        name: docker.pkg.github.com/Viss23/top-api/top-api
        username: ${{ secrets.Docker_USERNAME}}
        username: ${{ secrets.Docker_PASSWORD}}
        tags: "develop"
